### ISSUE TITLE
No support for custom attributes in openapi 2

### ISSUE THREAD

**Issue by jcarres-mdsol** [interagent/committee#219]
I have an openapi file like

```
/path:
    x-some-extensions:
      doc:
        ......
      slo:
        .....
    get:
      summary: Get All ,....
      parameters:
        - $ref: "#/parameters/..."
```

I get an exception:
```
undefined method `[]' for nil:NilClass (NoMethodError)
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:262:in `find_best_fit_response'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:350:in `block (2 levels) in parse_routes!'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:327:in `each'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:327:in `block in parse_routes!'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:322:in `each'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:322:in `parse_routes!'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers/open_api_2.rb:65:in `parse'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers.rb:61:in `load_from_data'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers.rb:29:in `load_from_yaml'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/drivers.rb:40:in `load_from_file'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/middleware/base.rb:28:in `get_schema'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/middleware/base.rb:9:in `initialize'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/committee-3.0.1/lib/committee/middleware/response_validation.rb:6:in `initialize'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:37:in `new'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:37:in `build'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `each'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `inject'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:101:in `build'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:510:in `block in app'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:506:in `synchronize'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:506:in `app'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/Users/jordi/.rvm/gems/ruby-2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/Users/jordi/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
```

I believe  the problem is `link_data["responses"]["200"]` where link_data is my `x-some-extensions` as there are no responses inside that block, that's nil and blows up.

**Comment by ota42y** [comment]
Thank you for the issue!
However, there is no openapi2 maintainer so it is very late to fix 🙇

**Comment by jcarres-mdsol** [comment]
No problem, close it if you want. Ourselves will move to openapi3 in the next few months so I do not think we will submit a fix for this

**Comment by ota42y** [comment]
Sorry... I close this.
